### ISSUE TITLE
2d polyline visualization slowing down in segmantation tool

### ISSUE THREAD

**Issue by luca-penasa** [cloudcompare/trunk#258] opened 2015-12-15 11:22 UTC
I recently noticed that the rendering of the 2d closed green polyline which follows the cursor when segmenting a point cloud tend to became sloppy from the SECOND time the tool is used (or at least it becomes sloppier each time it is used). Anybody ever noticed this same problem?

I mean that when moving the cursor the polyline open edge takes too much time to reach the new position of the cursor.

I am on Intel graphics, but I suspect this should not happen, it should not be such graphic-intensive task... 

Any idea?

**Comment by ORNis** [comment] 2015-12-15 11:35
Luca, I confirm this behavior, even on NVIDIA cards.

**Comment by luca-penasa** [comment] 2015-12-15 12:35
same behavior also if the internal pointer to polyline and vertexes are deleted and then reinitialized at each tool start() call...

**Comment by dgirardeau** [comment] 2015-12-15 12:52
I bet you are using the latest code? Because I thought I fixed something recently (but I might have break something else ;)

**Comment by ORNis** [comment] 2015-12-15 13:03
I'm using a 2.7.beta but an old one. As far as I remember I've had this problem for one year since (I was using CC for work). I thought it was my data and I use to reboot CC during long segmenting tasks to avoid this problem. 'Will give a try with latest git HEAD.

**Comment by luca-penasa** [comment] 2015-12-15 13:10
I am up to date with latest commits

**Comment by ORNis** [comment] 2015-12-15 13:51
@dgirardeau, it's nearly off-topic but I cant confirm that on current HEAD using segmentation tool could lead to a crash. Do you want my model to reproduce the issue ?

**Comment by dgirardeau** [comment] 2015-12-15 15:02
Definitely!

**Comment by ORNis** [comment] 2015-12-15 15:19
Ok I send you an email with some details.

**Comment by cloudcompare** [comment] 2015-12-15 19:37
I fixed the second bug (the Segmentation Tool bug). I created it whit my last commit... which was supposed to make the tool safer ;)

**Comment by cloudcompare** [comment] 2015-12-15 20:00
For the other bug, are you maybe using Qt 5?

**Comment by luca-penasa** [comment] 2015-12-16 09:33
Good catch :+1:  

It looks like its a qt5-related behavior...
Compiling with qt4 seems to solve the problem...
Is there a checklist of things not working fine with qt5? so to keep track of the issues related to qt5?

Short and unrelated question: is there any reason to not use openmp to speed up for loops in cloudcompare? Asking this cause I was using the pickPointCPU() method and it could be easily be distributed on the processors...

**Comment by cloudcompare** [comment] 2015-12-16 10:16
The main issue with Qt5 for me is the display of texts (it's not possible to display 3D text anymore - we have to find a way to do this on our own) and the 2D texts are buggy... There are also issues with some blacklisted graphic card drivers. And the strange fact that 3D displays (and maybe all the widgets) seem to be automatically updated about every second (this may explains your issue by the way).

**Comment by cloudcompare** [comment] 2015-12-16 10:18
And the prallel 'pickPointCPU' is a good idea. But I would prefer to use the Qt Concurrent framework (as all compilers don't support OpenMP - Visual Express 2010 and 2012 notably).

**Comment by ORNis** [comment] 2015-12-16 10:20
Ok sorry, I must say that my issue is quite different. So feel free to close this is issue when you find a consensus against qt-5 :). On my side I will open another issue when I find some time to document it.

**Comment by asmaloney** [comment] 2015-12-16 11:36
Just to followup on Daniel's point about OpenMP - it also isn't supported by default on Mac OS X (you need to install a different compiler), but as long as whatever you do is #ifdef guarded (like in the PoissonRecon plugin) it should be OK.

**Comment by luca-penasa** [comment] 2015-12-19 15:32
I suspect the problem is actually at these lines in ccGraphicalSegmantationTool.cpp

```cpp
ccGLWindow* oldWin = m_associatedWin;

	if (!ccOverlayDialog::linkWith(win))
		return false;

	if (oldWin)
	{
		m_associatedWin->disconnect(this);
		if (m_segmentationPoly)
			m_segmentationPoly->setDisplay(0);
	}
```

we are in fact disconnecting m_associatedWin from this, but we should disconnect the oldWin object instead. this causes multiple calls to the slots of this, probably making heavier the work of qt, and slowing down the rendering, each time more

What do you think Daniel?

**Comment by luca-penasa** [comment] 2015-12-19 15:41
Probably the bug comes out by the fact that we are calling linkWith before disconnecting the stuff. Thus one might think to have correctly disconnected oldWin after having disconnected m_associatedWin, but actually linkWith changed what m_associatedWin points to.... 
I see there are other parts in qCC in which this is made, maybe a check on the codebase is necessary?

**Comment by cloudcompare** [comment] 2015-12-19 19:44
You're right for this particular bug but this is something I changed (too quickly apparently ;) after you opened this issue...

I'll fix it tomorrow  (I don't have access to my computer right now) but I fear it might not solve everything...

**Comment by luca-penasa** [comment] 2015-12-19 20:00
Ah ok... I hoped to have found che trick :-)

**Comment by luca-penasa** [comment] 2015-12-21 09:37
I just tried and this explain the sloppiness of the 2d polyline on segmentation tool. Given much more points were added to the segmentation polyline due to multiple calls, this might have also influenced the computation time needed to perform the actual segmentation (?)

found the same problem in ccCameraParamEditDlg and ccSectionExtractionTool, Not filing a pull request cause Daniel might also know other places where to look for similar behaviors.

**Comment by ORNis** [comment] 2015-12-21 09:43
nice luca! Thanx

**Comment by dgirardeau** [comment] 2015-12-21 14:13
Perfect. I double checked all the equivalent methods (::linkWith) and hopefully this bug should be fixed.

**Closed by dgirardeau** 2015-12-21 14:13 UTC
