### ISSUE TITLE
Open .laz file crash OS X

### ISSUE THREAD

**Issue by macsurveyr** [cloudcompare/trunk#373] opened 2016-04-24 22:11 UTC
Attempting to open a .laz file with 2.7.0 will crash CloudCompare in Mac OS X El Capitan.

**Comment by asmaloney** [comment] 2016-04-24 22:17
I cannot reproduce this, but I don't have 10.11.  I can open the two .laz files I have on 10.10.

1) How big is the file?  Can you share it somehow?
2) Have you tried different .laz files?

**Comment by macsurveyr** [comment] 2016-04-24 22:28
I have tried many .laz files. I even tried some very small tiled .laz files. Uncompressed .las files open fine.

**Comment by forestgnome** [comment] 2016-04-27 09:16
I tried also with 10.11 and failed with .laz, but successfully opened all kinds of .las (130 Mio Points with ccViewer -> VERY IMPRESSIVE, many thanks!! )
-> do you uncompress .laz with OSX-tools or directly with LASTools ??

**Comment by asmaloney** [comment] 2016-04-27 12:03
I grabbed a bunch of random laszip files from sites pointed to on the [http://www.laszip.org/](lazip site) and they are working for me.  Could you please try some of them?

Again, I'll need some samples that aren't working for you.

> do you uncompress .laz with OSX-tools or directly with LASTools ??

I use the homebrew-built laszip:
```sh
$ brew info laszip
laszip: stable 2.2.0 (bottled), HEAD
Lossless LiDAR compression
http://www.laszip.org/
/Users/dev/Cellar/laszip/2.2.0 (14 files, 228.3K) *
  Built from source
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/laszip.rb
```

**Comment by macsurveyr** [comment] 2016-04-27 12:28
None of the files on laszip.org work either. FYI I use homebrew laszip as well

**Comment by asmaloney** [comment] 2016-04-27 12:30
Well that'll make it difficult to debug!  When I opened those, I just clicked through the dialogs to accept all the defaults - did you change any of the settings?

**Comment by macsurveyr** [comment] 2016-04-27 12:32
Cloudcompare crashes instantly when I click on Open.

**Comment by asmaloney** [comment] 2016-04-27 12:45
Offhand I can't think of why a change in OS version should affect just this - especially if laszip 2.2.0 from homebrew is working for you...

I guess we'll need a Mac developer who has a 10.11 environment set up to look into this.

Any takers?

**Comment by ORNis** [comment] 2016-04-27 12:47
Me, I will try in couple of hours.

**Comment by ORNis** [comment] 2016-04-27 18:41
I confirm it crash

**Comment by asmaloney** [comment] 2016-04-27 18:53
@ORNis I understand that it crashes - can you debug and fix it though?  :-)  I don't have 10.11 installed anywhere.

**Comment by ORNis** [comment] 2016-04-27 19:56
Ok.

**Comment by asmaloney** [comment] 2016-04-27 21:36
Alright - still don't know exactly what the problem is, but I've rebuilt the liblas/laszip libs a different way and it seems to work for @ORNis.

@macsurveyr and @forestgnome if you want to get in touch with me through my website I'll get you that build to try.

**Comment by asmaloney** [comment] 2016-04-27 22:17
The fix has been confirmed and will be included in the next release.

**Closed by asmaloney** 2016-04-27 22:17 UTC
Labels: MacOS

**Comment by forestgnome** [comment] 2016-06-06 12:53
@asmaloney ****
> ... I've rebuilt the liblas/laszip libs a different way ...
How can I get the new build or how to fix it ?
